### ISSUE TITLE
Implementation Question

### ISSUE THREAD

**Issue by cberg2048** [serverlesspub/ffmpeg-aws-lambda-layer#1]
I am trying to just do a hello world test with this layer. I deployed to my account successfully and am attempting to use the layer in a python3.6 runtime. 
I know this might not be appropriate for this forum but could you point me in the right direction for how to call the binary?

**Comment by gojko** [comment]
from python, use subprocess to execute the binary from `/opt/bin/ffmpeg` as you would do with any other binary
