### ISSUE TITLE
Is this can used for Node.js 12.x?

### ISSUE THREAD

**Issue by mikezang** [serverlesspub/ffmpeg-aws-lambda-layer#11]
I tried to use this layer and I added it to my function, but when I check if there exists about file /opt/ffmpeg/ffmpeg, I got not exists. may I have to do anything else except to add layer to my lambda function?

**Comment by gojko** [comment]
the binaries are in /opt/bin, not in /opt/ffmpeg

**Comment by ariel-frischer** [comment]
Will this work for node 12.x?

**Comment by gojko** [comment]
yes it will
