### ISSUE TITLE
Is nodejs.12 supported?

### ISSUE THREAD

**Issue by Nxtra** [serverlesspub/ffmpeg-aws-lambda-layer#17]
AWS is deprecating the nodejs.10 runtime.
Will this lambda layer keep working for lambda functions with nodejs.12 runtimes?

**Comment by andrewgwallace** [comment]
Yes. However, the easiest way is to first add the lambda layer from the SAM to your account. Create an appropriate bucket where you'd like the build to go, clone this repo and update template.yaml file to include` - nodejs12.x`. (I also added `= nodejs14.x` to the list). From there run the `make deploy` command and it will update the lambda layer you added from SAM in your lambda list.
Remember, this is merely a deployment of a static build of FFMPEG/FFPROBE so as long as they work with whatever version of node you've got running locally, it'll run here as well. 
Additionally, the make script downloads the latest available static version from John Van Sickle and, if not found, uses the local downloaded file. So in this case, when you run this you'll actually be building and deploying ffmpeg 4.4 (latest static build as of this comment).

**Comment by Nxtra** [comment]
Allright, that's good to know. Thanks.
Yes we deployed the layer using serverless framework. But the principle is the same.
\+  thanks for the extra info.
