### ISSUE TITLE
Subtitles doesn't work

### ISSUE THREAD

**Issue by Tribevote** [serverlesspub/ffmpeg-aws-lambda-layer#19]
I'm getting the below error 

`Fontconfig error: Cannot load default config file
[Parsed_subtitles_0 @ 0x5c39300] No usable fontconfig configuration file found, using fallback.
Fontconfig error: Cannot load default config file`

I'm guessing `libass` is not enabled by default, any idea on how to resolve this?

**Comment by andrewgwallace** [comment]
Sounds like you'll need to compile your own FFMPEG implementation with libass and then deploy that to SAM. I've not had a need for it just yet (though I see where I will at some point)
Maybe this will help?
https://trac.ffmpeg.org/wiki/CompilationGuide/macOS -- libass is listed in one of the examples. That's for macOS but I'm guessing the wiki has information on compiling for other systems as well.

**Comment by gojko** [comment]
if you're deploying on an awslinux 2 instance (eg nodejs12 and above, python 3.7), the linux distribution does not have fontconfig or freetype, so no method to load fonts. you can include fontconfig and freetype by recompiling manually, or use a docker lambda image and set up the appropriate dependencies that way
