### ISSUE TITLE
Error: You are not authorized to perform: lambda:GetLayerVersion

### ISSUE THREAD

**Issue by rmtuckerphx** [serverlesspub/ffmpeg-aws-lambda-layer#3]
I created a lambda function (Node.js 10.x) and in the AWS web console added the following layer:
arn:aws:lambda:us-east-1:145266761615:layer:ffmpeg:4

When I try to save, I get the error :
"You are not authorized to perform: lambda:GetLayerVersion."

Is this layer made to be used from any AWS account?
What do I need to do to allow this function to use the layer?

**Comment by gojko** [comment]
it's best to deploy the layer directly from the SAR to your account first, using the layer we deployed doesn't work across regions. Check out the usage section on this page https://github.com/serverlesspub/ffmpeg-aws-lambda-layer#usage
