### ISSUE TITLE
FFMPEG is truncating the audio files i'm trying to convert.

### ISSUE THREAD

**Issue by johandz** [serverlesspub/ffmpeg-aws-lambda-layer#6]
I'm trying to convert a .webm file to .mp3 running the following command within my lambda function.

`    os.system('/opt/bin/ffmpeg -acodec libopus -i /tmp/audioFile.{} -y -map 0 /tmp/output.mp3'.format(event['audioFormat']))
`

As long as the original audio file is bellow more or less 5 seconds, it gets transcoded correctly. However, if the file's longer, for some reason ffmpeg truncates it, and only convert the first seconds of the file. I've noticed that when truncating, the new file is always either 38.9, 39.4 or 39.8 KB in size.

Any Idea what might be going on??? 

Here are the logs:

ffmpeg version 4.1.3-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, matroska,webm, from '/tmp/audioFile.webm':
  Metadata:
    encoder         : Chrome
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Audio: opus, 48000 Hz, mono, s16 (default)
Stream mapping:
  Stream #0:0 -> #0:0 (opus (libopus) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
Output #0, mp3, to '/tmp/output.mp3':
  Metadata:
    TSSE            : Lavf58.20.100
    Stream #0:0(eng): Audio: mp3 (libmp3lame), 48000 Hz, mono, s16p (default)
    Metadata:
      encoder         : Lavc58.35.100 libmp3lame
Truncating packet of size 669363911 to 31787
size=      40kB time=00:00:05.05 bitrate=  64.5kbits/s speed=31.9x    
video:0kB audio:40kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.585012%

**Comment by gojko** [comment]
Hi, this is really a question for the ffmpeg project, not for this one; I just packaged the binary available from john as a Lambda layer.
